apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: bitwarden
    app: bitwarden
  name: bitwarden-data
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}